---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: devportal
  description: devPortal discovery demo
spec:
  owner: devportal
  domain: devportal.demo
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: portal
  description: Frontend web del portal
  labels:
    category: web
    team: frontend_team
  annotations:
    backstage.io/techdocs-ref: dir:.
    deployment_strategy: canary
  tags:
    - frontend
    - devportal
  urls:
    - url: https://github.com/codigitoes/catalog-test/blob/main/catalog-info.yaml
      type: documentation
    - url: https://github.com/codigitoes/catalog-test/blob/main/catalog-info.yaml
      type: git
spec:
  type: frontend
  lifecycle: production
  owner: devportal
  system: devportal
---