---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: devportal
  description: devPortal discovery demo
spec:
  owner: devportal
  domain: devportal.demo
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: portal
  description: Frontend web del portal
  labels:
    category: web
    team: frontend_team
  annotations:
    deployment_strategy: canary
  urls:
    - url: https://github.com/mi_empresa/portal
      type: git
spec:
  type: frontend
  lifecycle: production
  owner: devportal
  system: devportal
  dependencyOf:
    - resource:default/portal-private-library
  consumesApis:
    - portal-private-library
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: portal-private-library
  description: API library service privada del portal 
  labels:
    category: backend
    team: backend_team
  annotations:
    deployment_strategy: blue_green
  urls:
    - url: https://github.com/mi_empresa/portal-private-library
      type: git
spec:
  type: openapi
  lifecycle: production
  memberOf: devportal-services
  owner: devportal
  system: devportal
  dependsOn:
    - resource:default/portal-private-db
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: library API
      license:
        name: MIT
    servers:
      - url: http://library.company.net/v1
    paths:
      /library:
        get:
          summary: List all library
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: portal-private-db
  description: Base de datos exclusiva para el API privado del portal
  labels:
    category: database
    team: db_team
  annotations:
    backup_policy: weekly
  urls:
    - url: https://mi_empresa.com/db-portal
      type: documentation
spec:
  type: database
  lifecycle: production
  memberOf: devportal-services
  owner: devportal
  system: devportal
---