---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: devportal
  description: devPortal discovery demo
spec:
  owner: devportal
  domain: devportal.demo
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: portal
  description: Frontend web del portal
  labels:
    category: web
    team: frontend_team
  annotations:
    deployment_strategy: canary
  urls:
    - url: https://github.com/mi_empresa/portal
      type: git
spec:
  type: frontend
  lifecycle: production
  owner: devportal
  system: devportal
  consumesApis: ['resource:portal-private-access','resource:portal-private-library','resource:portal-private-details-library','resource:portal-private-details-terraforms']
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: portal-private-access
  description: API access service privada del portal 
  labels:
    category: backend
    team: backend_team
  annotations:
    deployment_strategy: blue_green
  urls:
    - url: https://github.com/mi_empresa/portal-private-access
      type: git
spec:
  type: openapi
  lifecycle: production
  memberOf: devportal-services
  owner: devportal
  system: devportal
  apiConsumedBy: ['component:portal']
  dependsOn: ['resource:portal-private-db']
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: access API
      license:
        name: MIT
    servers:
      - url: http://access.company.net/v1
    paths:
      /access:
        get:
          summary: List all access
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: portal-private-library
  description: API library service privada del portal 
  labels:
    category: backend
    team: backend_team
  annotations:
    deployment_strategy: blue_green
  urls:
    - url: https://github.com/mi_empresa/portal-private-library
      type: git
spec:
  type: openapi
  lifecycle: production
  memberOf: devportal-services
  owner: devportal
  system: devportal
  apiConsumedBy: ['component:portal']
  dependsOn: ['resource:portal-private-db']
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: library API
      license:
        name: MIT
    servers:
      - url: http://library.company.net/v1
    paths:
      /library:
        get:
          summary: List all library
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: portal-private-details-library
  description: API details library service privada del portal 
  labels:
    category: backend
    team: backend_team
  annotations:
    deployment_strategy: blue_green
  urls:
    - url: https://github.com/mi_empresa/portal-private-details-library
      type: git
spec:
  type: openapi
  lifecycle: production
  memberOf: devportal-services
  owner: devportal
  system: devportal
  apiConsumedBy: ['component:portal']
  dependsOn: ['resource:portal-private-db']
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: library API
      license:
        name: MIT
    servers:
      - url: http://library.company.net/v1
    paths:
      /details/library:
        get:
          summary: Details of library
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: portal-private-details-terraforms
  description: API details terraforms service privada del portal 
  labels:
    category: backend
    team: backend_team
  annotations:
    deployment_strategy: blue_green
  urls:
    - url: https://github.com/mi_empresa/portal-private-details-terraforms
      type: git
spec:
  type: openapi
  lifecycle: production
  memberOf: devportal-services
  owner: devportal
  system: devportal
  apiConsumedBy: ['component:portal']
  dependsOn: ['resource:portal-private-db']
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: terraforms API
      license:
        name: MIT
    servers:
      - url: http://terraforms.company.net/v1
    paths:
      /details/terraforms:
        get:
          summary: Details of terraforms
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: portal-private-db
  description: Base de datos exclusiva para el API privado del portal
  labels:
    category: database
    team: db_team
  annotations:
    backup_policy: weekly
  urls:
    - url: https://mi_empresa.com/db-portal
      type: documentation
spec:
  type: database
  lifecycle: production
  memberOf: devportal-services
  owner: devportal
  system: devportal
---
